### ISSUE TITLE
-webkit-background-clip: text error

### ISSUE THREAD

**Issue by theaceofweb** [1904labs/dom-to-image-more#26]
gives me an error any one cane help ?

.nav-link:hover,
.nav-link:focus{
    background: linear-gradient(to top, #ffe838, #fd57bf); 
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
}

**Comment by IDisposable** [comment]
What error? What platform/browser are you using? Can you give a minimal
reproduction in just HTML with inline CSS, and attach an image of what you
expect that to render?

**Comment by theaceofweb** [comment]
using chrome
this the code
![Screen Shot 1442-03-17 at 3 02 42 AM](https://user-images.githubusercontent.com/72704845/97932583-6bb5df00-1d81-11eb-88cb-f04c8bcb56b8.png)
what i should get is this 
![31231321321312](https://user-images.githubusercontent.com/72704845/97932605-7bcdbe80-1d81-11eb-8931-ae71750e22f2.png)
and this what am getting
![Screen Shot 1442-03-17 at 3 03 32 AM](https://user-images.githubusercontent.com/72704845/97932617-86885380-1d81-11eb-8db5-4076bcc19534.png)

**Comment by the-unknown** [comment]
I am having a similar issue.
My CSS:
```css
  .high-gloss-schwarz-3mm,
  .high-gloss-schwarz-6mm {
    background: linear-gradient(
      180deg,
      rgba(50, 50, 50, 0.95) 24%,
      rgba(186, 186, 186, 1) 45%,
      rgba(226, 235, 238, 0.9514006286108193) 49%,
      rgba(50, 50, 50, 0.93) 50%,
      rgba(50, 50, 50, 0.97) 100%
    );
    color: transparent;
    background-clip: text;
    text-shadow: rgba(0, 0, 0, 0.1) 5px 5px 10px;
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
  }
```
This is the result in Firefox (webkit-background-clip is not needed here). 
[![Firefox](https://i.imgur.com/xARvIWw.png)]

And this is the result of Chrome Mobile (webkit-background-clip is MANDATORY here): 
[![Chrome](https://i.imgur.com/w9F5Q1H.png)]
